// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MCMC_PSPI_generalizability
List MCMC_PSPI_generalizability(NumericMatrix X, NumericVector Y, NumericVector Z, NumericVector pi, NumericMatrix X_test, NumericVector pi_test, int model, long nburn, long npost, long n_knots_main, long n_knots_inter, long order_main, long order_inter, int ntrees_s, bool verbose);
RcppExport SEXP _PSPI_MCMC_PSPI_generalizability(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP piSEXP, SEXP X_testSEXP, SEXP pi_testSEXP, SEXP modelSEXP, SEXP nburnSEXP, SEXP npostSEXP, SEXP n_knots_mainSEXP, SEXP n_knots_interSEXP, SEXP order_mainSEXP, SEXP order_interSEXP, SEXP ntrees_sSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi_test(pi_testSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< long >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< long >::type npost(npostSEXP);
    Rcpp::traits::input_parameter< long >::type n_knots_main(n_knots_mainSEXP);
    Rcpp::traits::input_parameter< long >::type n_knots_inter(n_knots_interSEXP);
    Rcpp::traits::input_parameter< long >::type order_main(order_mainSEXP);
    Rcpp::traits::input_parameter< long >::type order_inter(order_interSEXP);
    Rcpp::traits::input_parameter< int >::type ntrees_s(ntrees_sSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(MCMC_PSPI_generalizability(X, Y, Z, pi, X_test, pi_test, model, nburn, npost, n_knots_main, n_knots_inter, order_main, order_inter, ntrees_s, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PSPI_MCMC_PSPI_generalizability", (DL_FUNC) &_PSPI_MCMC_PSPI_generalizability, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_PSPI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
