library(dplyr)
library(rstan)
library(brms)
library(RcppArmadillo)
library(Rcpp)
library(RcppDist)
library(boot)
library(SuperLearner)
library(readr)
sourceCpp("src/MCMC_BART_Causal.cpp")
MCMC_BART_Causal_R = function(X, Y, Z, pi, X_test, pi_test, model, nburn, npost, binary = F, verbose = F, seed = NULL, reverse = F, ntrees_s = 100){
  if(!is.null(seed))
    set.seed(seed)
  return(MCMC_BART_Causal(X, Y, Z, pi,  X_test, pi_test, model, nburn, npost, binary, verbose, reverse, ntrees_s))
}