# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCMC_PSPI_generalizability <- function(X, Y, Z, pi, X_test, pi_test, model, nburn, npost, n_knots_main, n_knots_inter, order_main = 3L, order_inter = 3L, ntrees_s = 200L, verbose = FALSE) {
    .Call(`_PSPI_MCMC_PSPI_generalizability`, X, Y, Z, pi, X_test, pi_test, model, nburn, npost, n_knots_main, n_knots_inter, order_main, order_inter, ntrees_s, verbose)
}

